USE [master]
GO

/****** Object:  Database [IngredientCalculator]    Script Date: 6/29/2018 9:52:19 AM ******/
CREATE DATABASE [IngredientCalculator]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IngredientCalculator', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\IngredientCalculator.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IngredientCalculator_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\IngredientCalculator_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [IngredientCalculator] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IngredientCalculator].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IngredientCalculator] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IngredientCalculator] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IngredientCalculator] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IngredientCalculator] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IngredientCalculator] SET ARITHABORT OFF 
GO

ALTER DATABASE [IngredientCalculator] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IngredientCalculator] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IngredientCalculator] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IngredientCalculator] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IngredientCalculator] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IngredientCalculator] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IngredientCalculator] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IngredientCalculator] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IngredientCalculator] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IngredientCalculator] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IngredientCalculator] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IngredientCalculator] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IngredientCalculator] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IngredientCalculator] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IngredientCalculator] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IngredientCalculator] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IngredientCalculator] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IngredientCalculator] SET RECOVERY FULL 
GO

ALTER DATABASE [IngredientCalculator] SET  MULTI_USER 
GO

ALTER DATABASE [IngredientCalculator] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IngredientCalculator] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IngredientCalculator] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IngredientCalculator] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [IngredientCalculator] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IngredientCalculator] SET  READ_WRITE 
GO


